### PR TITLE
feat: segregate community list alphabetically

### PR DESCRIPTION
**Pull request by httpjamesm**
In Apollo, the community list is sorted alphabetically but also separated by their starting letter. This makes it much clearer and easier to find communities in long lists.

Comparison (Apollo first, Wefwef second):
Screenshot 2023-06-29 at 18 33 36
Screenshot 2023-06-29 at 18 33 53

### CODE REVIEW

**Comment by aeharding** [comment]
Looks AWESOME!

 1. Let's useMemo the lodash logic
 2. Can you remove the typescript `as`? I can take a look too, no big deal :)

**Comment by httpjamesm** [comment]
Memoization done. I don't see a way to avoid using the `as` for the reduction map.

**Comment by aeharding** [comment]
Hi @httpjamesm, check out my changes and then I'll get this in for release tonight

**Comment by httpjamesm** [comment]
That's better. I forgot about the <> type indicator

**Pull request merged**
