### PR TITLE
Add button to message a user from their profile

### LINKED ISSUE #216: Send message to user from profile page
There should be a button to send a message to a user on the profile page you see when you click their name.

### PR DESCRIPTION
**Pull request by rsammelson**
Fixes #216

### CODE REVIEW

**Comment by aeharding** [comment]
Thanks for this. However we should implement this like Apollo did - with an ellipse to open an action sheet to provide actions (block , message etc)

**Comment by rsammelson** [comment]
@aeharding I think I fixed it

**Comment by aeharding** [comment]
Can you use the outline variant of the mail icon, and call it "Private Message"? Otherwise looks great :)

**Comment by aeharding** [comment]
Actually wait - the one other problem with this is that it changes the tab of the user. For best practice we shouldn't do that, which means the inbox stuff has to be part of a generic route (and we have to consider back button, etc)

I'm going to hold off on this release

**Comment by rsammelson** [comment]
Alright, I'll take a look at fixing this in the next couple days.

**Comment by rsammelson** [comment]
@aeharding how does Ionic know what tab is selected, I think I have it mostly working but when you go into it from posts it doesn't highlight any tab.

**Comment by aeharding** [comment]
If the URL starts with "posts" it should be highlighted

**Comment by rsammelson** [comment]
It did and there was no highlight,  but the page/highlight worked for all four other tabs, do you mind looking at some code once I get home and push it?

**Comment by rsammelson** [comment]
No tab selected, the URL is `/posts/other/messages/aeharding`.

**Comment by aeharding** [comment]
Should be fixed and ready to go now! :)

**Pull request merged**
