### PR TITLE
Clicking on feed post's image expands it

### PR DESCRIPTION
**Pull request by svrem**
Added the ability to expand the image of a feed post. This was a missing feature that was present in Apollo.

### CODE REVIEW

**Comment by aeharding** [comment]
Hello. Thanks for the PR. However this was not implemented intentionally, because there are no buttons in the Preview to jump to the post comments, reply, share etc. Once those are added we can do that

**Comment by svrem** [comment]
Thank you for reviewing my PR, but if I remember correctly there was no such button in Apollo either. I thought you were able to visit the detailed post by clicking on the black/white space surrounding the image. This is also the case in this PR, but please correct me if I remembered incorrectly!

**Comment by svrem** [comment]
Hi, thank you for reviewing it! I indeed forgot about those so I will be looking into implementing them too.

**Comment by aeharding** [comment]
Hey so an update, once #288 gets in the gallery component should be a LOT nicer :)

I added it here based on your logic but abstracted it so it's not duplicated code.

That's why I'm closing this, but I am going to add you as a co-author to my PR.

**Pull request closed without merging**
