### PR TITLE
Add support for sorting posts by time

### PR DESCRIPTION
**Pull request by mdecourcy**
Quick change to add support for sorting by time.

### CODE REVIEW

**Comment by GitBarns** [comment]
I thought this needed support in the Lemmy js library? I opened the issue a few days ago, would love to see this working! 

https://github.com/aeharding/wefwef/issues/34#issuecomment-1612082791

**Comment by mdecourcy** [comment]
> I thought this needed support in the Lemmy js library? I opened the issue a few days ago, would love to see this working! 
> 
> https://github.com/aeharding/wefwef/issues/34#issuecomment-1612082791
> 

Works on my end. The owner/contributors probably want a more nested modal IMO, like what was in Apollo. 

IE:
Top > Top hour
           Top day
Etc.

Tried to do something like that, but I'm more a backend guy.

**Comment by mdecourcy** [comment]
Also looks like that contributor was referring to comment sorting, not post sorting

**Comment by aeharding** [comment]
Yeah, I can take a look at it to implement nesting. This pr gets the conversation going at least, so thanks!

**Pull request merged**
