### PR TITLE
Feat: PostFeed post read style

### PR DESCRIPTION
**Pull request by robertnabbe**
Closes https://github.com/aeharding/wefwef/issues/146.

Screengrab of what this looks like for Large and Compact post settings in feed:

https://github.com/aeharding/wefwef/assets/13839643/50b83ca2-46ed-462c-b956-8e67c2cdb07e

### CODE REVIEW

**Comment by rsammelson** [comment]
`yarn test:typecheck` reports a type error:
src/features/post/inFeed/large/LargePost.tsx:178:8 - error TS2741: Property 'isRead' is missing

**Comment by robertnabbe** [comment]
Good find, my bad!

**Review by rsammelson — APPROVED** [review]

**Comment by rsammelson** [comment]
@aeharding should this be on a setting?

**Comment by aeharding** [comment]
I'm fine with it becoming a setting later.

@robertnabbe, the PR looks good! However, can you please change it so that this does not adjust the opacity of images? Only the title/description opacity should be adjusted.

Thanks!

**Comment by robertnabbe** [comment]
Definitely 👌

**Comment by aeharding** [comment]
Sorry, another conflict 😅 your PR is up next for merge

**Pull request merged**
