### PR TITLE
Double tap search button to start search

### LINKED ISSUE #61: Double tap search button to start search
Tapping the search button while already in the search tab should focus the search bar for easier navigation.

### PR DESCRIPTION
**Pull request by aidankinzett**
closes #61 

Implemented using a ref

### CODE REVIEW

**Comment by jmaruiz** [comment]
Nice job! Should you use .setFocus() instead per https://ionicframework.com/docs/api/searchbar ??

**Comment by aidankinzett** [comment]
> Nice job! Should you use .setFocus() instead per [ionicframework.com/docs/api/searchbar](https://ionicframework.com/docs/api/searchbar) ??

yes, I've updated to use that method

**Comment by aeharding** [comment]
Is there any documentation on createRef outside of components? 🤔 I've never seen this before.

PR works great though, and is nice and terse, so I'm just gonna merge lol

**Comment by aidankinzett** [comment]
> Is there any documentation on createRef outside of components? 🤔 I've never seen this before.
> 
> PR works great though, and is nice and terse, so I'm just gonna merge lol

Thanks. Just looking and I haven't found many docs about it, so now I'm not sure how supported it is haha. I mainly used it to avoid having to add the ref into some kind of state management system

**Pull request merged**
