### PR TITLE
feature: add cursor:pointer to post buttons

### LINKED ISSUE #115: Clickable areas should use "cursor:pointer" css, for better desktop browser UX
This is of course not an issue on mobile, but on desktop browsers, the text selection cursor is appearing throughout the interface, and a "pointer" (finger hand) cursor would be more appropriate.

### PR DESCRIPTION
**Pull request by tpkee**
Fixes #115

### CODE REVIEW

**Comment by aeharding** [comment]
Hi @tpkee thanks!

This looks great, however we could change these to <IonButton> (or just try normal html button if not easily workable) for better semantic html.

Do you want to try that? If not, I'll merge this in and take a look later.

**Comment by tpkee** [comment]
> Hi @tpkee thanks!
> 
> This looks great, however we could change these to (or just try normal html button if not easily workable) for better semantic html.
> 
> Do you want to try that? If not, I'll merge this in and take a look later.

Yeah sure, that's even better!

**Comment by tpkee** [comment]
> Hi @tpkee thanks!
> 
> This looks great, however we could change these to (or just try normal html button if not easily workable) for better semantic html.
> 
> Do you want to try that? If not, I'll merge this in and take a look later.

Done. I also modified the MoreActions component so that its options icon is not just an icon but an actual button.

**Comment by aeharding** [comment]
LGTM!

**Pull request merged**
