### PR TITLE
Basic settings page to import Reddit user data CSVs

### PR DESCRIPTION
**Pull request by yuletide**
Creating draft PR to track this work for #229 

Basic working implementation of a settings page to import subs from a reddit data export
image

Also unrelated but it would be nice to have a .prettierrc or prettier config block in the package.json for those of us who have prettier set to only format when one of those are around

### CODE REVIEW

**Comment by aeharding** [comment]
Nice work!

**Comment by yuletide** [comment]
@aeharding Thanks! Let me know if you notice anything glaring or I can take another pass before making it a full PR. I know you have lots moving rn!

**Comment by aeharding** [comment]
I've updated this to import from users' multireddit link. Then they don't have to wait for reddit export request :)

Hopefully that is OK!

**Comment by aeharding** [comment]
I suppose we could also have import from a reddit account data export request alongside. LMK if you feel strongly about it and we can add a generalized 'migrate' page with various migrate methods.

**Comment by aeharding** [comment]
Merging for now, though!

**Comment by yuletide** [comment]
@aeharding I haven't tried the multireddit approach, but if it achieves the same goal of importing all subreddits I think that is ok. We could also offer the other view as an option alongside it, for those that made their exports.

**Comment by aeharding** [comment]
Yeah, I was torn with deciding that 😅

Feel free to make another issue referencing this and we can pull it in!

We'll probably want to make a generic 'import from' page with various options so we don't clutter the main settings page if we go that route, too.

**Comment by yuletide** [comment]
Yeah that makes sense — import and then you can decide where from or we can
detect from the file somehow by type or headers

File input:
CSV - check for header and import as Reddit list (its just a new line
separated list anyways so could be from anything)
JSON - import as Apollo config structure

Or
Multireddit - paste your URL

**Comment by yuletide** [comment]
Ok I just saw the new flow and its very slick and makes sense to just do that instead of dealing with exports unless we are importing other things also like saved multireddits

**Pull request merged**
