### PR TITLE
feat: Detailed score and age alerts

### PR DESCRIPTION
**Pull request by httpjamesm**
When clicking on your comment/post karma counts or account age number in Apollo's profile section, it opens up a popup with more detailed information. This PR adds similar functionality.

image
image
image

### CODE REVIEW

**Comment by aeharding** [comment]
Hi! Can you remove the prettier changes from this PR? Then it will be easier to review. Thanks very much!

**Comment by aeharding** [comment]
Thanks for clearing up the formatting!

- Have you tried `useIonAlert`? That would probably reduce the amount of code quite a bit!
- I totally didn't know this feature existed in Apollo. So thanks so much for this PR!

**Comment by httpjamesm** [comment]
Unfortunately useIonAlert doesn't support multi-line messages, so I've instead separated it into a subheader and a message:

image

**Comment by aeharding** [comment]
I made a tweak to the PR to preserve newlines, and changed the `showScoreAlert` function.

I had to rebase due to conficts in `index.css`, so you will have to remove your local branch and re-pull if you want to get the changes locally.

This looks great though 😍 Review my changes quick and I'll get this in the next release!

**Comment by httpjamesm** [comment]
Yup, looks good!

**Pull request merged**
