### PR TITLE
Move toast above tab bar

### LINKED ISSUE #147: Toast messages should not appear over tab bar
In Apollo, toast messages come up from *below* the tab bar and move up to appear right above it, instead of on top of it in wefwef (which is super annoying since you cannot dismiss).

This will likely require some CSS ionic hacking to change what a toast considers the bottom of the page, along with z-index hacking.

But this is absolutely a quality of life thing. :)

Anyone is welcome to take a shot at this.

Bonus points for making an ionic feature request (or finding one) to swipe away toast messages

### PR DESCRIPTION
**Pull request by rsammelson**
This is currently a draft just to show a simple change that seems to at least improve the toast situation. I am also looking for feedback on if there is possibly a better way to do this.

Because of the hard coded offset some testing on various devices would be useful. This fixes #147, but not the extra feature of being able to swipe to dismiss.

### CODE REVIEW

**Comment by rsammelson** [comment]
It seems like it's not worth waiting on the swiping, so in the absence of a better approach this is probably ready to merge.

**Comment by aeharding** [comment]
This has problems when added to the homescreen, or when a dialog is open. :-(

Unfortunately, I'm not sure if there is a good way to accomplish this without a ionic lib change.

**Comment by rsammelson** [comment]
I will continue looking into it then.

**Comment by rsammelson** [comment]
I can't find a workable solution currently.

**Comment by aeharding** [comment]
Thanks for trying though @rsammelson :(

Looks like we will need to wait for an Ionic fix

**Pull request closed without merging**
