### PR TITLE
chore: add prettierrc and format

### PR DESCRIPTION
**Pull request by httpjamesm**
- Adds a `.prettierrc` config to the root directory of the project so that new contributors' formatting extensions will adhere to the existing tab spacing, quotation formality, etc.

### CODE REVIEW

**Comment by aeharding** [comment]
Hello! Thanks very much for the PR!

A couple comments:

 - wefwef is using prettier's defaults (without a `.prettierrc`). It's what [elk](https://github.com/elk-zone/elk) does too, I believe. I would like to keep using those defaults, if possible!
 - I now realize that there is not build step in the CI to check prettier, so I should probably add that 😅 (unless you want to?)

**Comment by httpjamesm** [comment]
This prettier config uses all the defaults, but also adds the trailing commas requirement. My prettier defaults have wider indentations which were messing up the formatting.

If you're not up for the trailing commas, it can be removed.

**Comment by aeharding** [comment]
That's strange. Prettier doesn't have a global configuration, I'm pretty sure.

> Prettier intentionally doesn’t support any kind of global configuration. This is to make sure that when a project is copied to another computer, Prettier’s behavior stays the same. Otherwise, Prettier wouldn’t be able to guarantee that everybody in a team gets the same consistent results.

https://prettier.io/docs/en/configuration.html

Maybe there is an environment issue? Or do you use editorconfig and maybe that's breaking something? Could you try an editorconfig with root = true and see if that resolves your issues?

**Comment by httpjamesm** [comment]
I don't have an editor config and adding `root = true` didn't work. Not quite sure...

**Comment by httpjamesm** [comment]
Ah I see. It's because I set the tab width in my VSCode prettier extension to 4 some time ago. I usually use 4 for my other projects, so maybe it's still beneficial to keep a prettier config here?

**Comment by aeharding** [comment]
Yeah, that's fine. We could also add an editorconfig with indent size. As long as it doesn't change the existing code formatting.

**Comment by aeharding** [comment]
I'm going to close this - feel free to open a new PR with the prettier file (if it doesn't change existing code formatting)

**Pull request closed without merging**
