### PR TITLE
Setting to have comments threads collapsed by default

### LINKED ISSUE #130: Setting to have comments collapsed by default
It would be great if comment threads could be collapsed by default via a setting.

### PR DESCRIPTION
**Pull request by tpkee**
Closes #130 

Probably there is some (or a lot!) of work to do here. Particularly, I would check out the useEffect used in the CommentTree component. Right now I don't have a better idea, so it may be fine but I would check it out twice

### CODE REVIEW

**Comment by aeharding** [comment]
Hi Thanks for this.

However, I think we need a different approach.

We should get only one level deep when the mode is to collapse children.

Then, the comment should use its data to determine if there are more comments to load in. It should then display how many more replies they are, like this:

image

When tapped, the comments for that node should be fetched and appended to the tree.

This would also solve problems with only being able to see 8 levels deep.

This might involve a bit of refactor, so if you would like, you can change this to just include the setting and I will merge this to a feature branch.

**Comment by tpkee** [comment]
> Hi Thanks for this.
> 
> However, I think we need a different approach.
> 
> We should get only one level deep from the API when the mode is to collapse children.
> 
> Then, the comment should use its data to determine if there are more comments to load in. It should then display how many more replies they are, like this:
> 
> image
> When tapped, the comments for that node should be fetched and appended to the tree.
> 
> This would also solve problems with only being able to see 8 levels deep.
> 
> This might involve a bit of refactor, so if you would like, you can change this to just include the setting and I will merge this to a feature branch.

Oh yeah, that's much better!
I dropped the commit in which I include the functionality, leaving just the new setting option. I pushed the change so you can open the feature branch. I'll try to work on it tomorrow, but no guarantee

**Comment by aeharding** [comment]
Thank you very much :)

**Comment by aeharding** [comment]
I am currently working on this.

**Pull request merged**
